### ISSUE TITLE
[Featured request]: can you add the facility for limit the selection with mulitple option

### ISSUE THREAD

**Issue by yatinB07** [mazipan/vue-select-image#19]
Hi,

As image-picker library provides the option like:
      limit: void 0,
      limit_reached: void 0,
for setting the limit for multi-select, it would be great if get the same facility with Vue.

for reference: http://rvera.github.io/image-picker/
topic: "Limit multiple selects" 

. thanks in advance

**Comment by mazipan** [comment]
Released 1.9.0 with limit support
