### ISSUE TITLE
Import bug in Readme

### ISSUE THREAD

**Issue by eossa** [mazipan/vue-select-image#4]
Hi, I import the component as the docs suggest
`import VueSelectImage from 'VueSelectImage'`

But throws exception when compiling
`Module not found: Error: Can't resolve 'VueSelectImage'`

I solved with this change
`import VueSelectImage from 'vue-select-image'`

Do you think that the docs needs to be updated?

**Comment by mazipan** [comment]
Yes, will do.
Thanks
