### ISSUE TITLE
How to give style a specific image

### ISSUE THREAD

**Issue by recep-yildiz** [mazipan/vue-select-image#50]
There are "id", "src" and "alt" propse, how to give style to a specific image?

**Comment by mazipan** [comment]
I just release 1.8.0 with id on each image

**Comment by ItStark** [comment]
Id prop can't be seen on DOM, so i can't access to give it a style?

Let's say that I have 10 images (Ids: [0, 1, 2... 9]), I want to make 8. id img grayscale, how to achieve this?

**Comment by recep-yildiz** [comment]
It was necessary, Thank you so much.
