### ISSUE TITLE
Dont have a watcher for the props

### ISSUE THREAD

**Issue by arisnacg** [mazipan/vue-select-image#6]
You need update..

The Component need update the dataImagesLocal property everytime dataImages props change

Sorry for bad english

**Comment by mazipan** [comment]
Ah yes, I just initialize in `created` hook, should move to computed.
So will update anything in props.

Will update soon

**Comment by arisnacg** [comment]
Nice one

**Comment by mazipan** [comment]
Dont forget to give ⭐️  yap... :-P
