### ISSUE TITLE
set initial selection

### ISSUE THREAD

**Issue by ad34** [mazipan/vue-select-image#7]
I'm currently trying to set an initial selection but looks like filling the array declared in  @onselectmultipleimage but update the selection. is there any way to do this?

**Comment by mazipan** [comment]
Not possible for now, but I can add in next release.
Or if you want di your own implementation, just fork and feel free to open pull request.
I will review your code.

Thanks

**Comment by mirkos93** [comment]
You can do it by accessing the reference directly.
For example:
```html
<vue-select-image ref="imageSelector"></vue-select-image>
```

For multiple selection:
```js
const images = [
    { id: '...', src: '...'},
    //...
];
this.$refs.imageSelector.multipleSelected = images;
```

For single selection (not tested):
```js
const image_id = '...';
this.$set(this.$refs.imageSelector.singleSelected, 'id', image_id);
```

**Comment by mazipan** [comment]
I do not recommend using `$refs`, use `props` `:selectedImages` with Array type.
You can also doing for singleSelection with same way.
